# see https://github.com/marketplace/actions/license-eye-header#configurations

header:
  # this is not the actual license, but the desired compatibility
  license:
    spdx-id: Apache-2.0
    copyright-year: 2026
    copyright-owner: Zaphiro Technologies

  paths-ignore:
    - ".github"
    - "**/*.{md,MD}"
    - "LICENSE"
    - "package.json"
    - "yarn.lock"

  comment: on-failure
